version: "3.8"

services:
    alfresco:
        image: alfresco/alfresco-content-repository-community:$APP_VERSION
        container_name: $APP_CONTAINER_NAME-content
        restart: always
        deploy:
            resources:
              limits:
                memory: 1500M
        environment:
            JAVA_TOOL_OPTIONS: "
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
                "
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=$DB_POSTGRESQL_PASSWORD
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.http.connection.timeout=1000
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=$APP_SITE_URL
                -Dshare.port=8080
                -Dalfresco.host=$APP_SITE_URL
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
                -Dcsrf.filter.enabled=false
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                "

    transform-core-aio:
        image: alfresco/alfresco-transform-core-aio:2.3.10
        container_name: $APP_CONTAINER_NAME-transform
        restart: always
        deploy:
            resources:
              limits:
                memory: 1536M
        environment:
            JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8090:8090
            
    shared-file-store:
      image: alfresco/alfresco-shared-file-store:0.16.0
      mem_limit: 512m
      environment:
        JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
        scheduler.content.age.millis: 86400000
        scheduler.cleanup.interval: 86400000
      ports:
        - "8099:8099"
      volumes:
        - shared-file-store-volume:/tmp/Alfresco/sfs
        
    share:
        image: alfresco/alfresco-share:$APP_VERSION
        container_name: $APP_CONTAINER_NAME-share
        restart: always
        deploy:
            resources:
              limits:
                memory: 1G
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: "
                -XX:MinRAMPercentage=50
                -XX:MaxRAMPercentage=80
                -Dalfresco.host=$APP_SITE_URL
                -Dalfresco.port=8080
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "
        volumes: 
            - $VOLUMES_PATH_PREFIX/alfresco/share/logs:/usr/local/tomcat/logs

    postgres:
        image: postgres:$DB_POSTGRESQL_VERSION
        container_name: $APP_CONTAINER_NAME-postgres
        restart: always
        deploy:
            resources:
              limits:
                memory: 512M
        environment:
            - POSTGRES_PASSWORD=$DB_POSTGRESQL_PASSWORD
            - POSTGRES_USER=$DB_POSTGRESQL_USER
            - POSTGRES_DB=$DB_POSTGRESQL_NAME
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - $DB_POSTGRESQL_PORT:5432
        volumes: 
            - $VOLUMES_PATH_PREFIX/postgres/data:/var/lib/postgresql/data
            - $VOLUMES_PATH_PREFIX/postgres/logs:/var/log/postgresql

    solr6:
        image: alfresco/alfresco-search-services:2.0.1
        container_name: $APP_CONTAINER_NAME-solr6
        restart: always
        deploy:
            resources:
              limits:
                memory: 2G
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
            #HTTP by default
            - ALFRESCO_SECURE_COMMS=none
        ports:
            - 8083:8983 #Browser port

    activemq:
        image: alfresco/alfresco-activemq:$MQ_ACTIVEMQ_VERSION
        container_name: $APP_CONTAINER_NAME-activemq
        restart: always
        deploy:
            resources:
              limits:
                memory: 1G
        ports:
            - $MQ_ACTIVEMQ_PORT:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP
    
    proxy:
        image: alfresco/alfresco-acs-nginx:3.1.1
        container_name: $APP_CONTAINER_NAME-proxy
        restart: always
        deploy:
            resources:
              limits:
                memory: 128M
        environment:
            DISABLE_PROMETHEUS: "true"
            DISABLE_SYNCSERVICE: "true"
            DISABLE_ADW: "true"
        depends_on:
            - alfresco
        ports:
            - $APP_PORT:8080
        links:
            - alfresco
            - share

networks:
    default:
        name: "$APP_NETWORK"

volumes:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
